site_name: ReactiveState
repo_name: ReactiveState-Kotlin
repo_url: https://github.com/ensody/ReactiveState-Kotlin
site_description: "An easy to understand reactive state management solution for Kotlin and Android"
site_author: Ensody GmbH
copyright: 'Copyright &copy; 2020 Ensody GmbH'

remote_branch: gh-pages

theme:
  name: 'material'
  logo: 'images/ensody.svg'
  favicon: 'images/favicon.ico'
  features:
    - navigation.expand

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - 'API reference':
    - 'reactivestate': reference/reactivestate/com.ensody.reactivestate/index.md
    - 'reactivestate-test': reference/reactivestate-test/com.ensody.reactivestate.test/index.md
  - 'Changelog': changelog.md
