site_name: ReactiveState-Android
repo_name: ReactiveState-Android
repo_url: https://github.com/ensody/ReactiveState-Android
site_description: "An easy to understand reactive state management solution for Android"
site_author: Ensody GmbH
copyright: 'Copyright &copy; 2020 Ensody GmbH'

remote_branch: gh-pages

theme:
  name: 'material'
  logo: 'images/ensody.svg'
  favicon: 'images/favicon.ico'

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - 'API reference': reactivestate/index.md
  - 'Change Log': changelog.md
