[tool.poetry]
name = "ReactiveState-Android"
version = "0.6.0"
description = "ReactiveState-Android"
authors = []

[tool.poetry.dependencies]
python = "^3.6"
mkdocs = "^1.1"
mkdocs-material = "^5.1.1"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
