version: '3.1'

services:

  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspace:cached
      - ~/.ssh/config:/root/.ssh-localhost/config:ro
      - ~/.ssh/known_hosts:/root/.ssh-localhost/known_hosts:ro
    command: /bin/bash -c "set -euo pipefail; /workspace/.devcontainer/build-post-create.sh; while sleep 1000; do :; done"
